apiVersion: apps/v1
kind: Deployment
metadata:
  name: demo-fe
  labels:
    app: demo-fe
spec:
  selector:
    matchLabels:
      app: demo-fe
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
  template:
    metadata:
      labels:
        app: demo-fe
    spec:
      containers:
        - image: farhat18/demo-fe:latest 
          name: demo-fe
          imagePullPolicy: Always
          resources:
            limits:
              memory: 800Mi
              cpu: 800m
            requests:
              memory: 500Mi
              cpu: 500m
          ports:
            - containerPort: 80
              name: demo-fe
